C The original program is modified such that the inputs are taken from fort.11 and results for perpenducular polarization are written to fort.12
      PROGRAM CALLBHCYL
      COMPLEX REFREL,T1(200),T2(200)
      DIMENSION ANG(200)
      DATA PI/3.1415927E0/
      WRITE(*,*)'CALL CYLINDER PROGRAM, NORMALLY INCIDENT LIGHT'
C REFMED=REFRACTIVE INDEX OF MEDIUM
      REFMED=1.0
C REFREL=REFRACTIVE INDEX OF CYLINDER/REFMED
      read(11,*) REFRE
      read(11,*) REFIM
      read(11,*) RAD
      read(11,*) WAVE
      read(11,*) FIN
      read(11,*) INTANG
c 1000 WRITE(*,*)'ENTER COMPLEX REFRACTIVE INDEX OF CYLINDER'
c      READ(*,*)REFREL
       REFREL=CMPLX(REFRE,REFIM)	
       REFREL=REFREL/REFMED
c      WRITE(*,*)'ENTER RADIUS (in the units of wavelength)'
c      READ(*,*)RAD
c      WRITE(*,*)'ENTER WAVELENGTH (in the units of radius)' 
c      READ(*,*)WAVE
       X=2.E0*PI*RAD*REFMED/WAVE
c      WRITE(*,*)'ENTER FINAL ANGLE IN DEGREES'
c      READ(*,*)FIN
c      WRITE(*,*)'ENTER NUMBER OF INTERVALS BETWEEN 0 AND FIN'
c      READ(*,*)INTANG
      WRITE(*, *) REFRE
      WRITE(*, *) REFIM
      WRITE(*, *) RAD
      WRITE(*, *) WAVE
      WRITE(*, *) FIN
      WRITE(*, *) INTANG
 0011 FORMAT(1X, F8.2)
      WRITE(*,0015)
 0015 FORMAT(/,2X,'ANGLE',7X,'T11',13X,'POL',13X,'T33',13X,'T34',//)
      CALL BHCYL(X,REFREL,T1,T2,QSCPAR,QSCPER,QEXPAR,QEXPER,
     &FIN,INTANG,ANG)
      NPTS=INTANG+1
      T11NOR=0.5*(CABS(T1(1))*CABS(T1(1)))
      T11NOR=T11NOR+0.5*(CABS(T2(1))*CABS(T2(1)))
C*** T33 AND T34 MATRIX ELEMENTS NORMALIZED BY T11
C    T11 IS NORMALIZED TO 1.0 IN THE FORWARD DIRECTION
C    POL=DEGREE OF POLARIZATION (INCIDENT UNPOLARIZED LIGHT)
      DO 0107 J=1,NPTS
      TPAR=CABS(T1(J))
      TPAR=TPAR*TPAR
      TPER=CABS(T2(J))
      TPER=TPER*TPER
      T11=0.5E0*(TPAR+TPER)
      T12=0.5E0*(TPAR-TPER)
      POL=T12/T11
      T33=REAL(T1(J)*CONJG(T2(J)))
      T34=AIMAG(T1(J)*CONJG(T2(J)))
      T33=T33/T11
      T34=T34/T11
      T11=T11/T11NOR
 0107 WRITE(*,0068)ANG(J),T11,POL,T33,T34
      WRITE(*,0067)QSCPAR,QEXPAR,QSCPER,QEXPER
      WRITE(12,*)QSCPER,QEXPER
 0067 FORMAT(/,' QSCPAR =',1PE14.6,3X,'QEXPAR =',E14.6,/,
     &' QSCPER =',E14.6,3X,'QEXPER =',E14.6,/)
 0068 FORMAT(1X,F8.2,2X,1PE13.6,2X,E13.6,2X,E13.6,2X,E13.6)
c     GOTO 1000
      END
